/*
 * Jian Engine C ABI
 *
 * This header has one ABI shape in every build. Rust feature flags and debug
 * assertions never add, remove, or alter declarations in this contract.
 *
 * Coordinates: pointer input and all text-geometry inputs/outputs use
 * surface-logical pixels with a top-left origin.
 *
 * Tail-growth versioning: JianCreateDesc.size must be at least
 * offsetof(JianCreateDesc, dpr) + sizeof(float) (36 bytes on the supported
 * 64-bit hosts). JianCallbacks.size must be at least sizeof(size_t) (8 bytes
 * on the supported 64-bit hosts). Missing trailing fields are zero/null; a
 * size larger than the current sizeof(struct) is invalid.
 *
 * Android setComposingText newCursorPosition conversion (UTF-16 units): let S
 * be the replacement/composing start, L the UTF-16 length of the new text,
 * and N Android's newCursorPosition. The absolute cursor is
 * N > 0 ? S + L + N - 1 : S + N, clamped to the final text bounds. For
 * jian_ime_set_composing_text, pass the in-composition cursor relative to S
 * as both sel_start and sel_end; if the clamped cursor is outside the new
 * composing range, set the absolute selection with jian_text_set_selection
 * immediately after the composing call. jian_ime_commit accepts N directly.
 */


#ifndef JIAN_H
#define JIAN_H

/* Generated by cbindgen 0.29.4. Regenerate; do not edit this file directly. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Stable status values returned by every Jian C ABI call.
 */
enum JianStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  JianStatus_Ok = 0,
  JianStatus_InvalidArg = 1,
  JianStatus_BadDocument = 2,
  JianStatus_LayoutError = 3,
  JianStatus_GpuError = 4,
  JianStatus_OutOfMemory = 5,
  JianStatus_WrongThread = 6,
  JianStatus_Suspended = 7,
  JianStatus_Busy = 8,
  JianStatus_NoFocus = 9,
  JianStatus_NotReady = 10,
  JianStatus_Poisoned = 11,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum JianStatus JianStatus;
#else
typedef int32_t JianStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum JianRuntimeErrorKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  JianRuntimeErrorKind_Layout = 0,
  JianRuntimeErrorKind_Action = 1,
  JianRuntimeErrorKind_Internal = 2,
  JianRuntimeErrorKind_Warning = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum JianRuntimeErrorKind JianRuntimeErrorKind;
#else
typedef int32_t JianRuntimeErrorKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum JianInputKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  JianInputKind_Text = 0,
  JianInputKind_Number = 1,
  JianInputKind_Secure = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum JianInputKind JianInputKind;
#else
typedef int32_t JianInputKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum JianReturnKeyHint
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  JianReturnKeyHint_Default = 0,
  JianReturnKeyHint_Done = 1,
  JianReturnKeyHint_Go = 2,
  JianReturnKeyHint_Next = 3,
  JianReturnKeyHint_Search = 4,
  JianReturnKeyHint_Send = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum JianReturnKeyHint JianReturnKeyHint;
#else
typedef int32_t JianReturnKeyHint;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum JianCapabilityKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  JianCapabilityKind_HttpFetch = 0,
  JianCapabilityKind_Confirm = 1,
  JianCapabilityKind_ClipboardRead = 2,
  JianCapabilityKind_ClipboardWrite = 3,
  JianCapabilityKind_ImageFetch = 4,
  JianCapabilityKind_OpenUrl = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum JianCapabilityKind JianCapabilityKind;
#else
typedef int32_t JianCapabilityKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum JianWritingDirection
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  JianWritingDirection_LeftToRight = 0,
  JianWritingDirection_RightToLeft = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum JianWritingDirection JianWritingDirection;
#else
typedef int32_t JianWritingDirection;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum JianImeControlOp
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  JianImeControlOp_Commit = 0,
  JianImeControlOp_Cancel = 1,
  JianImeControlOp_Dismiss = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum JianImeControlOp JianImeControlOp;
#else
typedef int32_t JianImeControlOp;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum JianPointerPhase
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  JianPointerPhase_Down = 0,
  JianPointerPhase_Move = 1,
  JianPointerPhase_Up = 2,
  JianPointerPhase_Cancel = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum JianPointerPhase JianPointerPhase;
#else
typedef int32_t JianPointerPhase;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum JianTextGranularity
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  JianTextGranularity_Character = 0,
  JianTextGranularity_Word = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum JianTextGranularity JianTextGranularity;
#else
typedef int32_t JianTextGranularity;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

typedef struct JianEngine JianEngine;

/**
 * Platform surface descriptor. On iOS `handle` is a borrowed CAMetalLayer*.
 */
typedef struct {
  size_t size;
  void *handle;
} JianSurfaceDesc;

typedef struct {
  const uint8_t *name_ptr;
  size_t name_len;
  const uint8_t *value_ptr;
  size_t value_len;
} JianHeader;

typedef struct {
  bool ok;
  uint16_t status;
  const JianHeader *headers;
  size_t headers_len;
  const uint8_t *body_ptr;
  size_t body_len;
  const uint8_t *error_ptr;
  size_t error_len;
} JianHttpFetchResult;

typedef struct {
  bool value;
} JianConfirmResult;

typedef struct {
  bool ok;
  const uint8_t *text_ptr;
  size_t text_len;
  const uint8_t *error_ptr;
  size_t error_len;
} JianClipboardReadResult;

typedef struct {
  bool ok;
  const uint8_t *error_ptr;
  size_t error_len;
} JianClipboardWriteResult;

typedef struct {
  bool ok;
  const uint8_t *bytes_ptr;
  size_t bytes_len;
  const uint8_t *error_ptr;
  size_t error_len;
} JianImageFetchResult;

typedef struct {
  bool ok;
  const uint8_t *error_ptr;
  size_t error_len;
} JianOpenUrlResult;

typedef union {
  JianHttpFetchResult http_fetch;
  JianConfirmResult confirm;
  JianClipboardReadResult clipboard_read;
  JianClipboardWriteResult clipboard_write;
  JianImageFetchResult image_fetch;
  JianOpenUrlResult open_url;
} JianCapabilityResultData;

typedef struct {
  size_t size;
  int32_t kind;
  JianCapabilityResultData data;
} JianCapabilityResult;

typedef void (*JianNeedsRedraw)(void *user_data, bool has_next_wake, uint64_t next_wake_ms);

/**
 * Borrowed diagnostic payload, valid only for the callback duration.
 */
typedef struct {
  size_t size;
  JianRuntimeErrorKind kind;
  const uint8_t *message_ptr;
  size_t message_len;
  const uint8_t *source_ptr;
  size_t source_len;
} JianRuntimeError;

typedef void (*JianRuntimeErrorCallback)(void *user_data, const JianRuntimeError *error);

typedef void (*JianImeControl)(void *user_data, int32_t op, uint64_t request_id);

typedef struct {
  size_t size;
  JianInputKind input_kind;
  JianReturnKeyHint return_key_hint;
} JianFieldInfo;

typedef void (*JianInputFocusChanged)(void *user_data, bool focused, const JianFieldInfo *info);

typedef void (*JianTextStateChanged)(void *user_data);

typedef struct {
  const uint8_t *method_ptr;
  size_t method_len;
  const uint8_t *url_ptr;
  size_t url_len;
  const JianHeader *headers;
  size_t headers_len;
  bool has_body;
  const uint8_t *body_ptr;
  size_t body_len;
  bool has_timeout;
  uint64_t timeout_ms;
} JianHttpFetchRequest;

typedef struct {
  const uint8_t *title_ptr;
  size_t title_len;
  const uint8_t *message_ptr;
  size_t message_len;
} JianConfirmRequest;

typedef struct {
  uint8_t reserved;
} JianClipboardReadRequest;

typedef struct {
  const uint8_t *text_ptr;
  size_t text_len;
} JianClipboardWriteRequest;

typedef struct {
  const uint8_t *url_ptr;
  size_t url_len;
} JianImageFetchRequest;

typedef struct {
  const uint8_t *url_ptr;
  size_t url_len;
} JianOpenUrlRequest;

typedef union {
  JianHttpFetchRequest http_fetch;
  JianConfirmRequest confirm;
  JianClipboardReadRequest clipboard_read;
  JianClipboardWriteRequest clipboard_write;
  JianImageFetchRequest image_fetch;
  JianOpenUrlRequest open_url;
} JianCapabilityRequestData;

typedef struct {
  size_t size;
  JianCapabilityKind kind;
  JianCapabilityRequestData data;
} JianCapabilityRequest;

typedef void (*JianCapabilityRequestCallback)(void *user_data,
                                              uint64_t request_id,
                                              const JianCapabilityRequest *request);

typedef void (*JianCapabilityCancelled)(void *user_data, uint64_t request_id);

/**
 * Callback table. Future callbacks grow only at the tail.
 */
typedef struct {
  size_t size;
  void *user_data;
  JianNeedsRedraw needs_redraw;
  JianRuntimeErrorCallback runtime_error;
  JianImeControl ime_control;
  JianInputFocusChanged input_focus_changed;
  JianTextStateChanged text_state_changed;
  JianCapabilityRequestCallback capability_request;
  JianCapabilityCancelled capability_cancelled;
} JianCallbacks;

/**
 * Engine construction descriptor. `asset_base` is the v1 tail.
 */
typedef struct {
  size_t size;
  const uint8_t *doc_ptr;
  size_t doc_len;
  float width;
  float height;
  float dpr;
  const uint8_t *storage_dir_ptr;
  size_t storage_dir_len;
  const JianCallbacks *callbacks;
  const uint8_t *asset_base_ptr;
  size_t asset_base_len;
} JianCreateDesc;

typedef struct {
  float x;
  float y;
  float width;
  float height;
} JianRect;

/**
 * Borrowed surrounding-text window. `text_ptr` remains valid until the next
 * call on this engine; all offsets are absolute UTF-16 code-unit offsets.
 */
typedef struct {
  size_t size;
  const uint8_t *text_ptr;
  size_t text_len;
  uint32_t window_start;
  uint32_t selection_start;
  uint32_t selection_end;
  bool has_composing;
  uint32_t composing_start;
  uint32_t composing_end;
} JianTextState;

typedef struct {
  JianRect rect;
  JianWritingDirection writing_direction;
} JianTextRect;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Select GPU mode using a borrowed platform surface.
 *
 * # Safety
 *
 * Pointers must be live and the surface must outlive attach through suspend.
 */
JianStatus jian_attach_surface(JianEngine *engine, const JianSurfaceDesc *desc);

/**
 * Complete an outstanding platform capability request.
 *
 * # Safety
 * `engine` must be live and `result` must expose a complete result struct.
 */
JianStatus jian_capability_result(JianEngine *engine,
                                  uint64_t request_id,
                                  const JianCapabilityResult *result);

/**
 * Create an engine from a versioned descriptor.
 *
 * # Safety
 *
 * `desc` must expose its declared prefix and `out` must be writable.
 */
JianStatus jian_create(const JianCreateDesc *desc, JianEngine **out);

/**
 * Destroy an engine on its owner thread.
 *
 * # Safety
 *
 * `engine` must be live, returned by `jian_create`, and not yet destroyed.
 */
JianStatus jian_destroy(JianEngine *engine);

/**
 * Pump and present one GPU frame.
 *
 * # Safety
 *
 * `engine` must be live and called on its owner thread.
 */
JianStatus jian_frame(JianEngine *engine, uint64_t now_ms);

/**
 * Pump and copy one CPU frame into caller-owned RGBA8888 storage.
 *
 * # Safety
 *
 * `engine` must be live and `buffer` must cover `buffer_len` writable bytes.
 */
JianStatus jian_frame_cpu(JianEngine *engine,
                          uint64_t now_ms,
                          uint8_t *buffer,
                          size_t buffer_len,
                          size_t stride);

/**
 * Return the current physical pixel dimensions.
 *
 * # Safety
 *
 * `engine` must be live and both output pointers must be writable.
 */
JianStatus jian_get_pixel_size(JianEngine *engine, uint32_t *width, uint32_t *height);

/**
 * Cancel local preedit or confirm cancellation of an engine request.
 *
 * # Safety
 *
 * `engine` must be live and called on its owner thread.
 */
JianStatus jian_ime_cancel(JianEngine *engine, uint64_t request_id);

/**
 * Commit platform text, optionally confirming an engine request.
 *
 * # Safety
 *
 * `engine` must be live and `text` must cover `length` readable bytes.
 */
JianStatus jian_ime_commit(JianEngine *engine,
                           const uint8_t *text,
                           size_t length,
                           int32_t new_cursor_position,
                           uint64_t request_id);

/**
 * Select durable text as the composing region.
 *
 * # Safety
 *
 * `engine` must be live and called on its owner thread.
 */
JianStatus jian_ime_set_composing_region(JianEngine *engine, uint32_t start, uint32_t end);

/**
 * Set platform preedit and its composing-relative selection.
 *
 * # Safety
 *
 * `engine` must be live and `text` must cover `length` readable bytes.
 */
JianStatus jian_ime_set_composing_text(JianEngine *engine,
                                       const uint8_t *text,
                                       size_t length,
                                       uint32_t selection_start,
                                       uint32_t selection_end);

/**
 * Copy the last error into a caller-owned byte buffer.
 *
 * # Safety
 *
 * A non-null `engine` must be live; output pointers must cover their sizes.
 */
JianStatus jian_last_error(JianEngine *engine, uint8_t *buffer, size_t length, size_t *required);

/**
 * Dispatch one touch event in surface-logical coordinates.
 *
 * # Safety
 *
 * `engine` must be live and called on its owner thread.
 */
JianStatus jian_pointer(JianEngine *engine,
                        uint32_t id,
                        int32_t phase,
                        float x,
                        float y,
                        uint64_t now_ms);

/**
 * Register a TTF/OTF face in Jian's process-global Skia registry.
 *
 * # Safety
 * `engine` must be live and `bytes` must cover `length` readable bytes.
 */
JianStatus jian_register_font(JianEngine *engine, const uint8_t *bytes, size_t length);

/**
 * Change the logical viewport and device-pixel ratio.
 *
 * # Safety
 *
 * `engine` must be live and called on its owner thread.
 */
JianStatus jian_resize(JianEngine *engine, float width, float height, float dpr);

/**
 * Resume rendering, optionally with a new borrowed GPU surface.
 *
 * # Safety
 *
 * `engine` must be live; a non-null descriptor must be readable.
 */
JianStatus jian_resume(JianEngine *engine, const JianSurfaceDesc *desc);

/**
 * Update the logical keyboard occlusion height.
 *
 * # Safety
 *
 * `engine` must be live and called on its owner thread.
 */
JianStatus jian_set_keyboard(JianEngine *engine, float height);

/**
 * Update the four logical safe-area insets.
 *
 * # Safety
 *
 * `engine` must be live and called on its owner thread.
 */
JianStatus jian_set_safe_area(JianEngine *engine, float top, float right, float bottom, float left);

/**
 * Suspend rendering and synchronously stop using a borrowed surface.
 *
 * # Safety
 *
 * `engine` must be live and called on its owner thread.
 */
JianStatus jian_suspend(JianEngine *engine);

/**
 * Begin a batch of platform text edits.
 *
 * # Safety
 *
 * `engine` must be live and called on its owner thread.
 */
JianStatus jian_text_batch_begin(JianEngine *engine);

/**
 * End a batch of platform text edits.
 *
 * # Safety
 *
 * `engine` must be live and called on its owner thread.
 */
JianStatus jian_text_batch_end(JianEngine *engine);

/**
 * Return the caret rectangle for the current selection focus.
 *
 * # Safety
 *
 * `engine` must be live and `output` must be writable.
 */
JianStatus jian_text_caret_rect(JianEngine *engine, JianRect *output);

/**
 * Return the caret rectangle for an explicit UTF-16 offset.
 *
 * # Safety
 *
 * `engine` must be live and `output` must be writable.
 */
JianStatus jian_text_caret_rect_for_offset(JianEngine *engine, uint32_t offset, JianRect *output);

/**
 * Copy an arbitrary effective-text range into a caller buffer.
 *
 * # Safety
 *
 * `engine` must be live; output pointers must cover their declared sizes.
 */
JianStatus jian_text_get_range(JianEngine *engine,
                               uint32_t start,
                               uint32_t end,
                               uint8_t *buffer,
                               size_t length,
                               size_t *required);

/**
 * Return a borrowed surrounding-text window and absolute ranges.
 *
 * # Safety
 *
 * `engine` must be live and `output` must expose its declared writable size.
 */
JianStatus jian_text_get_state(JianEngine *engine, JianTextState *output);

/**
 * Insert or replace the current platform selection.
 *
 * # Safety
 *
 * `engine` must be live and `text` must cover `length` readable bytes.
 */
JianStatus jian_text_insert(JianEngine *engine, const uint8_t *text, size_t length);

/**
 * Hit-test a surface-logical point to a UTF-16 text position.
 *
 * # Safety
 *
 * `engine` must be live and `output` must be writable.
 */
JianStatus jian_text_position_at_point(JianEngine *engine, float x, float y, uint32_t *output);

/**
 * Hit-test a surface-logical point to a UAX #29 text range.
 *
 * # Safety
 *
 * `engine` must be live and both range outputs must be writable.
 */
JianStatus jian_text_range_at_point(JianEngine *engine,
                                    float x,
                                    float y,
                                    int32_t granularity,
                                    uint32_t *start,
                                    uint32_t *end);

/**
 * Return shaped selection rectangles and the total required count.
 *
 * # Safety
 *
 * `engine` must be live; `output` must cover `capacity` elements and `count`
 * must be writable.
 */
JianStatus jian_text_rects_for_range(JianEngine *engine,
                                     uint32_t start,
                                     uint32_t end,
                                     JianTextRect *output,
                                     size_t capacity,
                                     size_t *count);

/**
 * Replace an effective-text range.
 *
 * # Safety
 *
 * `engine` must be live and `text` must cover `length` readable bytes.
 */
JianStatus jian_text_replace_range(JianEngine *engine,
                                   uint32_t start,
                                   uint32_t end,
                                   const uint8_t *text,
                                   size_t length);

/**
 * Set the effective platform selection.
 *
 * # Safety
 *
 * `engine` must be live and called on its owner thread.
 */
JianStatus jian_text_set_selection(JianEngine *engine, uint32_t start, uint32_t end);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* JIAN_H */
