// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A single Action is a 1-key object: `{ "<action_name>": <body> }`.
 *
 * Examples (all are valid JSON `Action`s):
 * - `{ "set": { "$state.count": "$state.count + 1" } }`
 * - `{ "fetch": { "url": "/api/x", "into": "$state.u" } }`
 * - `{ "push": "/detail/42" }`
 *
 * The body shape per action is NOT validated here — see `jian-core::action`.
 */
export type Action = { [key in string]?: JsonValue };

export type AlignItems = "start" | "center" | "end";

export type AppConfig = { name: string, version: string, id: string, entry: string | null, capabilities: Array<Capability> | null, theme: string | null, orientation: Orientation | null, backgroundColor: string | null, icon: string | null, 
/**
 * C19 splash-frame config.
 */
splash: SplashConfig | null, 
/**
 * C18 ASP web handshake postMessage origin allowlist.
 * Only consulted by the web host; strict match; no wildcards.
 */
aspAllowedOrigins: Array<string> | null, };

export type AppLifecycleHooks = { onLaunch: Array<Action> | null, onResume: Array<Action> | null, onBackground: Array<Action> | null, onTerminate: Array<Action> | null, };

export type BlendMode = "normal" | "darken" | "multiply" | "screen" | "overlay" | "lighten" | "difference" | "hue" | "saturation" | "color" | "luminosity";

export type BlurBody = { radius: number, };

/**
 * Boolean that may also be an expression.
 */
export type BoolOrExpression = boolean | string;

export type Capability = "storage" | "network" | "camera" | "microphone" | "location" | "notifications" | "clipboard" | "biometric" | "file_system" | "haptic";

export type CornerRadius = number | [number, number, number, number];

export type EllipseNode = { width: SizingBehavior | null, height: SizingBehavior | null, cornerRadius: number | null, innerRadius: number | null, startAngle: number | null, sweepAngle: number | null, fill: Array<PenFill> | null, stroke: PenStroke | null, effects: Array<PenEffect> | null, state: { [key in string]?: StateEntry } | null, bindings: { [key in string]?: Expression } | null, events: EventHandlers | null, lifecycle: NodeLifecycleHooks | null, semantics: SemanticsMeta | null, gestures: GestureOverrides | null, route: NavigationRoute | null, id: string, name: string | null, role: string | null, explain: string | null, x: number | null, y: number | null, rotation: number | null, opacity: NumberOrExpression | null, enabled: BoolOrExpression | null, visible: boolean | null, locked: boolean | null, flipX: boolean | null, flipY: boolean | null, theme: { [key in string]?: string } | null, };

/**
 * All supported event hook keys. Note: input events (`onChange`, `onSubmit`, `onFocus`,
 * `onBlur`) apply only to input-kind nodes. `on_key` is keyboard, `on_reach_end`
 * is list-scroll-end, etc.
 */
export type EventHandlers = { onTap: Array<Action> | null, onDoubleTap: Array<Action> | null, onLongPress: Array<Action> | null, onPanStart: Array<Action> | null, onPanUpdate: Array<Action> | null, onPanEnd: Array<Action> | null, onScaleStart: Array<Action> | null, onScaleUpdate: Array<Action> | null, onScaleEnd: Array<Action> | null, onRotateStart: Array<Action> | null, onRotateUpdate: Array<Action> | null, onRotateEnd: Array<Action> | null, onHoverEnter: Array<Action> | null, onHoverLeave: Array<Action> | null, onChange: Array<Action> | null, onSubmit: Array<Action> | null, onFocus: Array<Action> | null, onBlur: Array<Action> | null, onKey: Array<Action> | null, onScroll: Array<Action> | null, onReachEnd: Array<Action> | null, };

/**
 * A Tier 1 expression source — represented as a raw string.
 *
 * Parsing and validation are the responsibility of `jian-core::expression::parser`
 * (Plan 2). The schema crate only guarantees the string is present; content-level
 * correctness is deferred.
 */
export type Expression = string;

export type FontStyleKind = "normal" | "italic";

export type FontWeight = number | string;

/**
 * Forward declaration of PenNode union — defined in `node/mod.rs`.
 * We accept `Vec<super::PenNode>` as children.
 */
export type FrameNode = { children: Array<PenNode> | null, reusable: boolean | null, slot: Array<string> | null, state: { [key in string]?: StateEntry } | null, bindings: { [key in string]?: Expression } | null, events: EventHandlers | null, lifecycle: NodeLifecycleHooks | null, semantics: SemanticsMeta | null, gestures: GestureOverrides | null, route: NavigationRoute | null, id: string, name: string | null, role: string | null, explain: string | null, x: number | null, y: number | null, rotation: number | null, opacity: NumberOrExpression | null, enabled: BoolOrExpression | null, visible: boolean | null, locked: boolean | null, flipX: boolean | null, flipY: boolean | null, theme: { [key in string]?: string } | null, width: SizingBehavior | null, height: SizingBehavior | null, layout: LayoutMode | null, gap: NumberOrExpression | null, padding: Padding | null, justifyContent: JustifyContent | null, alignItems: AlignItems | null, clipContent: boolean | null, cornerRadius: CornerRadius | null, fill: Array<PenFill> | null, stroke: PenStroke | null, effects: Array<PenEffect> | null, };

export type GestureOverrides = { 
/**
 * When true, this node and its subtree bypass the Arena and receive raw pointer events.
 */
rawPointer: boolean | null, disabled: Expression | null, scrollBehavior: ScrollBehavior | null, 
/**
 * Override drag threshold in logical pixels (default 8).
 */
dragThreshold: number | null, 
/**
 * Override long-press duration in ms (default 500).
 */
longPressDuration: number | null, };

export type GradientStop = { offset: number, color: string, };

export type GroupNode = { children: Array<PenNode> | null, state: { [key in string]?: StateEntry } | null, bindings: { [key in string]?: Expression } | null, events: EventHandlers | null, lifecycle: NodeLifecycleHooks | null, semantics: SemanticsMeta | null, gestures: GestureOverrides | null, route: NavigationRoute | null, id: string, name: string | null, role: string | null, explain: string | null, x: number | null, y: number | null, rotation: number | null, opacity: NumberOrExpression | null, enabled: BoolOrExpression | null, visible: boolean | null, locked: boolean | null, flipX: boolean | null, flipY: boolean | null, theme: { [key in string]?: string } | null, width: SizingBehavior | null, height: SizingBehavior | null, layout: LayoutMode | null, gap: NumberOrExpression | null, padding: Padding | null, justifyContent: JustifyContent | null, alignItems: AlignItems | null, clipContent: boolean | null, cornerRadius: CornerRadius | null, fill: Array<PenFill> | null, stroke: PenStroke | null, effects: Array<PenEffect> | null, };

export type IconFontNode = { iconFontName: string, iconFontFamily: string | null, width: SizingBehavior | null, height: SizingBehavior | null, fill: Array<PenFill> | null, stroke: PenStroke | null, state: { [key in string]?: StateEntry } | null, bindings: { [key in string]?: Expression } | null, events: EventHandlers | null, lifecycle: NodeLifecycleHooks | null, semantics: SemanticsMeta | null, gestures: GestureOverrides | null, route: NavigationRoute | null, id: string, name: string | null, role: string | null, explain: string | null, x: number | null, y: number | null, rotation: number | null, opacity: NumberOrExpression | null, enabled: BoolOrExpression | null, visible: boolean | null, locked: boolean | null, flipX: boolean | null, flipY: boolean | null, theme: { [key in string]?: string } | null, };

export type ImageFillBody = { url: string, mode: ImageFillMode | null, originalSize: ImageOriginalSize | null, transform: ImageTransform | null, explain: string | null, opacity: number | null, exposure: number | null, contrast: number | null, saturation: number | null, temperature: number | null, tint: number | null, highlights: number | null, shadows: number | null, };

export type ImageFillMode = "fill" | "fit" | "crop" | "tile" | "stretch";

export type ImageFitMode = "fill" | "fit" | "crop" | "tile";

export type ImageNode = { src: string, objectFit: ImageFitMode | null, width: SizingBehavior | null, height: SizingBehavior | null, cornerRadius: CornerRadius | null, effects: Array<PenEffect> | null, exposure: number | null, contrast: number | null, saturation: number | null, temperature: number | null, tint: number | null, highlights: number | null, shadows: number | null, imagePrompt: string | null, imageSearchQuery: string | null, state: { [key in string]?: StateEntry } | null, bindings: { [key in string]?: Expression } | null, events: EventHandlers | null, lifecycle: NodeLifecycleHooks | null, semantics: SemanticsMeta | null, gestures: GestureOverrides | null, route: NavigationRoute | null, id: string, name: string | null, role: string | null, explain: string | null, x: number | null, y: number | null, rotation: number | null, opacity: NumberOrExpression | null, enabled: BoolOrExpression | null, visible: boolean | null, locked: boolean | null, flipX: boolean | null, flipY: boolean | null, theme: { [key in string]?: string } | null, };

export type ImageOriginalSize = { width: number, height: number, };

export type ImageTransform = { m00: number, m01: number, m02: number, m10: number, m11: number, m12: number, };

export type JustifyContent = "start" | "center" | "end" | "space_between" | "space_around";

export type LayoutMode = "none" | "vertical" | "horizontal";

export type LineNode = { x2: number | null, y2: number | null, stroke: PenStroke | null, effects: Array<PenEffect> | null, state: { [key in string]?: StateEntry } | null, bindings: { [key in string]?: Expression } | null, events: EventHandlers | null, lifecycle: NodeLifecycleHooks | null, semantics: SemanticsMeta | null, gestures: GestureOverrides | null, route: NavigationRoute | null, id: string, name: string | null, role: string | null, explain: string | null, x: number | null, y: number | null, rotation: number | null, opacity: NumberOrExpression | null, enabled: BoolOrExpression | null, visible: boolean | null, locked: boolean | null, flipX: boolean | null, flipY: boolean | null, theme: { [key in string]?: string } | null, };

export type LinearGradientBody = { angle: number | null, stops: Array<GradientStop>, explain: string | null, opacity: number | null, blendMode: BlendMode | null, };

export type LiveRegion = "off" | "polite" | "assertive";

/**
 * An ABI version string for the Tier 3 WASM module. The only recognised
 * value today is `jian.wasm.v1`; Jian rejects unknown ABI at load time.
 */
export type LogicAbi = string;

export type LogicModuleRef = { id: string, source: string, integrity: string | null, abi: LogicAbi, capabilities: Array<Capability> | null, };

/**
 * Declarative per-node navigation: clicking the node pushes/replaces/pops a route.
 * Equivalent to `events.on_tap = [{"push": "..."}]` but more editor-discoverable.
 */
export type NavigationRoute = { "push": string } | { "replace": string } | { "pop": null };

export type NodeLifecycleHooks = { onMount: Array<Action> | null, onUnmount: Array<Action> | null, };

/**
 * Opacity can be a number or a `$variable` reference string.
 */
export type NumberOrExpression = number | string;

export type Orientation = "portrait" | "landscape" | "auto";

export type Padding = number | [number, number] | [number, number, number, number] | string;

export type PageLifecycleHooks = { onEnter: Array<Action> | null, onLeave: Array<Action> | null, onForeground: Array<Action> | null, onBackground: Array<Action> | null, };

export type PathNode = { iconId: string | null, d: string | null, anchors: Array<PenPathAnchor> | null, closed: boolean | null, width: SizingBehavior | null, height: SizingBehavior | null, fill: Array<PenFill> | null, stroke: PenStroke | null, effects: Array<PenEffect> | null, state: { [key in string]?: StateEntry } | null, bindings: { [key in string]?: Expression } | null, events: EventHandlers | null, lifecycle: NodeLifecycleHooks | null, semantics: SemanticsMeta | null, gestures: GestureOverrides | null, route: NavigationRoute | null, id: string, name: string | null, role: string | null, explain: string | null, x: number | null, y: number | null, rotation: number | null, opacity: NumberOrExpression | null, enabled: BoolOrExpression | null, visible: boolean | null, locked: boolean | null, flipX: boolean | null, flipY: boolean | null, theme: { [key in string]?: string } | null, };

export type PenDocument = { 
/**
 * Document format version stored in files since v0.x. Always present.
 */
version: string, name: string | null, 
/**
 * Wire shape: axis-name → ordered theme names. Frozen from v0.x.
 */
themes: { [key in string]?: Array<string> } | null, variables: { [key in string]?: VariableDefinition } | null, pages: Array<PenPage> | null, children: Array<PenNode>, 
/**
 * "1.0" when any v1 extension is present; undefined ⇒ legacy v0.x.
 */
formatVersion: string | null, 
/**
 * App id (reverse-DNS). Required when `app` is set; otherwise optional.
 */
id: string | null, app: AppConfig | null, routes: RoutesConfig | null, state: { [key in string]?: StateEntry } | null, lifecycle: AppLifecycleHooks | null, logicModules: Array<LogicModuleRef> | null, };

export type PenEffect = { "type": "blur" } & BlurBody | { "type": "background_blur" } & BlurBody | { "type": "shadow" } & ShadowBody;

export type PenFill = { "type": "solid" } & SolidFillBody | { "type": "linear_gradient" } & LinearGradientBody | { "type": "radial_gradient" } & RadialGradientBody | { "type": "image" } & ImageFillBody;

/**
 * Union of all concrete node types.
 * Tag is the JSON `"type"` field.
 */
export type PenNode = { "type": "frame" } & FrameNode | { "type": "group" } & GroupNode | { "type": "rectangle" } & RectangleNode | { "type": "ellipse" } & EllipseNode | { "type": "line" } & LineNode | { "type": "polygon" } & PolygonNode | { "type": "path" } & PathNode | { "type": "text" } & TextNode | { "type": "text_input" } & TextInputNode | { "type": "image" } & ImageNode | { "type": "icon_font" } & IconFontNode | { "type": "ref" } & RefNode;

export type PenPage = { id: string, name: string, children: Array<PenNode>, state: { [key in string]?: StateEntry } | null, lifecycle: PageLifecycleHooks | null, };

export type PenPathAnchor = { x: number, y: number, handleIn: PenPathHandle | null, handleOut: PenPathHandle | null, pointType: PenPathPointType | null, };

export type PenPathHandle = { x: number, y: number, };

export type PenPathPointType = "corner" | "mirrored" | "independent";

export type PenStroke = { thickness: StrokeThickness, align: StrokeAlign | null, join: StrokeJoin | null, cap: StrokeCap | null, dashPattern: Array<number> | null, dashOffset: number | null, fill: Array<PenFill> | null, };

export type PolygonNode = { polygonCount: number, width: SizingBehavior | null, height: SizingBehavior | null, cornerRadius: number | null, fill: Array<PenFill> | null, stroke: PenStroke | null, effects: Array<PenEffect> | null, state: { [key in string]?: StateEntry } | null, bindings: { [key in string]?: Expression } | null, events: EventHandlers | null, lifecycle: NodeLifecycleHooks | null, semantics: SemanticsMeta | null, gestures: GestureOverrides | null, route: NavigationRoute | null, id: string, name: string | null, role: string | null, explain: string | null, x: number | null, y: number | null, rotation: number | null, opacity: NumberOrExpression | null, enabled: BoolOrExpression | null, visible: boolean | null, locked: boolean | null, flipX: boolean | null, flipY: boolean | null, theme: { [key in string]?: string } | null, };

export type PrimitiveType = "int" | "float" | "number" | "string" | "bool" | "array" | "object" | "date";

export type RadialGradientBody = { cx: number | null, cy: number | null, radius: number | null, stops: Array<GradientStop>, explain: string | null, opacity: number | null, blendMode: BlendMode | null, };

export type RectangleNode = { children: Array<PenNode> | null, state: { [key in string]?: StateEntry } | null, bindings: { [key in string]?: Expression } | null, events: EventHandlers | null, lifecycle: NodeLifecycleHooks | null, semantics: SemanticsMeta | null, gestures: GestureOverrides | null, route: NavigationRoute | null, id: string, name: string | null, role: string | null, explain: string | null, x: number | null, y: number | null, rotation: number | null, opacity: NumberOrExpression | null, enabled: BoolOrExpression | null, visible: boolean | null, locked: boolean | null, flipX: boolean | null, flipY: boolean | null, theme: { [key in string]?: string } | null, width: SizingBehavior | null, height: SizingBehavior | null, layout: LayoutMode | null, gap: NumberOrExpression | null, padding: Padding | null, justifyContent: JustifyContent | null, alignItems: AlignItems | null, clipContent: boolean | null, cornerRadius: CornerRadius | null, fill: Array<PenFill> | null, stroke: PenStroke | null, effects: Array<PenEffect> | null, };

export type RefNode = { ref: string, descendants: { [key in string]?: JsonValue } | null, children: Array<PenNode> | null, state: { [key in string]?: StateEntry } | null, bindings: { [key in string]?: Expression } | null, events: EventHandlers | null, lifecycle: NodeLifecycleHooks | null, semantics: SemanticsMeta | null, gestures: GestureOverrides | null, route: NavigationRoute | null, id: string, name: string | null, role: string | null, explain: string | null, x: number | null, y: number | null, rotation: number | null, opacity: NumberOrExpression | null, enabled: BoolOrExpression | null, visible: boolean | null, locked: boolean | null, flipX: boolean | null, flipY: boolean | null, theme: { [key in string]?: string } | null, };

export type RouteSpec = { pageId: string, preload: boolean | null, guards: Array<Action> | null, 
/**
 * Path-parameter type declarations (v1.0 additive — 2026-04-24).
 * Keys correspond to `:param` placeholders in the route path
 * (e.g. path `/detail/:id` → key `id`). The AI Action Surface
 * uses these types when synthesising the JsonSchema for the
 * derived `open_*(p)` action; runtime does strict type-checking
 * on incoming values rather than silent coercion.
 */
params: { [key in string]?: StateType } | null, };

export type RoutesConfig = { entry: string, routes: { [key in string]?: RouteSpec }, transitions: { [key in string]?: Transition } | null, };

export type ScrollBehavior = "auto" | "contain" | "none";

export type SemanticAction = { name: string, label: string, handler: Array<Action>, };

export type SemanticRole = "button" | "link" | "image" | "text" | "heading" | "input" | "list" | "list_item" | "header" | "nav" | "main" | "dialog" | "alert";

export type SemanticsMeta = { role: SemanticRole | null, label: string | null, hint: string | null, liveRegion: LiveRegion | null, disabled: Expression | null, actions: Array<SemanticAction> | null, 
/**
 * Author-stable override for the auto-derived AI action name.
 * When set, the resulting action name is `<scope>.<aiName>`
 * without the auto `_<hash4>` suffix and survives slug recomputes
 * across builds. See `2026-04-24-ai-action-surface.md` §3.3-3.4.
 */
aiName: string | null, 
/**
 * Tool description shown to external AI agents. Overrides the
 * auto-generated default; lets authors steer what a model "sees"
 * without changing visible UI text.
 */
aiDescription: string | null, 
/**
 * `true` permanently hides the node's derived action from the AI
 * surface (StaticHidden). Defaults to `false`. ConfirmGated /
 * StateGated availability are decided dynamically and do **not**
 * require this flag — see ai-action-surface.md §4.
 */
aiHidden: boolean | null, 
/**
 * Historical `aiName` values still accepted by `execute_action`
 * for transparent migration after a rename. Aliases are honoured
 * at execute time (with `audit reason_code: "alias_used"`) but
 * not surfaced by `list_available_actions`. See §9.
 */
aiAliases: Array<string> | null, };

export type ShadowBody = { inner: boolean | null, offsetX: number, offsetY: number, blur: number, spread: number, color: string, };

export type SidedThickness = { top: number | null, right: number | null, bottom: number | null, left: number | null, };

/**
 * Sizing value: a number, a fixed keyword, or an arbitrary string (typically `$variable` ref).
 */
export type SizingBehavior = number | SizingKeyword | string;

export type SizingKeyword = "fit_content" | "fill_container";

export type SolidFillBody = { color: string, explain: string | null, opacity: number | null, blendMode: BlendMode | null, };

export type SplashConfig = { background: string | null, image: string | null, text: string | null, minDurationMs: number | null, };

export type StateEntry = { type: StateType, default: JsonValue | null, description: string | null, persist: boolean | null, };

/**
 * Recursive state type description.
 */
export type StateType = PrimitiveType | { oneOf: Array<StateType>, } | { array: StateType, } | { object: { [key in string]?: StateType }, };

export type StrokeAlign = "inside" | "center" | "outside";

export type StrokeCap = "none" | "round" | "square";

export type StrokeJoin = "miter" | "bevel" | "round";

export type StrokeThickness = number | [number, number, number, number] | SidedThickness;

export type StyledTextSegment = { text: string, fontFamily: string | null, fontSize: number | null, fontWeight: number | null, fontStyle: FontStyleKind | null, fill: string | null, underline: boolean | null, strikethrough: boolean | null, href: string | null, };

export type TextAlign = "left" | "center" | "right" | "justify";

export type TextAlignVertical = "top" | "middle" | "bottom";

export type TextContent = string | Array<StyledTextSegment>;

export type TextGrowth = "auto" | "fixed-width" | "fixed-width-height";

/**
 * Single-line text input. Forms / counters need a writable input
 * surface that two-way binds via `bindings.bind:value`. The walker
 * renders a styled rectangle + caret placeholder; full IME and
 * selection-painter wiring lands in the desktop host (Plan 8) once
 * the gesture arena gains `Focus` recognizers.
 */
export type TextInputNode = { width: SizingBehavior | null, height: SizingBehavior | null, 
/**
 * Placeholder shown when `value` is empty. Static text — author
 * `bindings.placeholder` if it needs to react to state.
 */
placeholder: string | null, 
/**
 * Initial value. Two-way binding lives on `bindings.bind:value`,
 * which derive lifts into a `set_*` action and the runtime keeps
 * in sync with the state graph.
 */
value: string | null, fill: Array<PenFill> | null, stroke: PenStroke | null, effects: Array<PenEffect> | null, state: { [key in string]?: StateEntry } | null, bindings: { [key in string]?: Expression } | null, events: EventHandlers | null, lifecycle: NodeLifecycleHooks | null, semantics: SemanticsMeta | null, gestures: GestureOverrides | null, route: NavigationRoute | null, id: string, name: string | null, role: string | null, explain: string | null, x: number | null, y: number | null, rotation: number | null, opacity: NumberOrExpression | null, enabled: BoolOrExpression | null, visible: boolean | null, locked: boolean | null, flipX: boolean | null, flipY: boolean | null, theme: { [key in string]?: string } | null, };

export type TextNode = { width: SizingBehavior | null, height: SizingBehavior | null, content: TextContent, fontFamily: string | null, fontSize: number | null, fontWeight: FontWeight | null, fontStyle: FontStyleKind | null, letterSpacing: number | null, lineHeight: number | null, textAlign: TextAlign | null, textAlignVertical: TextAlignVertical | null, textGrowth: TextGrowth | null, underline: boolean | null, strikethrough: boolean | null, fill: Array<PenFill> | null, effects: Array<PenEffect> | null, state: { [key in string]?: StateEntry } | null, bindings: { [key in string]?: Expression } | null, events: EventHandlers | null, lifecycle: NodeLifecycleHooks | null, semantics: SemanticsMeta | null, gestures: GestureOverrides | null, route: NavigationRoute | null, id: string, name: string | null, role: string | null, explain: string | null, x: number | null, y: number | null, rotation: number | null, opacity: NumberOrExpression | null, enabled: BoolOrExpression | null, visible: boolean | null, locked: boolean | null, flipX: boolean | null, flipY: boolean | null, theme: { [key in string]?: string } | null, };

export type ThemedValue = { value: VariableScalar, theme: { [key in string]?: string } | null, };

export type Transition = "push" | "fade" | "modal" | "none";

export type VariableDefinition = { type: VariableKind, value: VariableValue, };

export type VariableKind = "color" | "number" | "boolean" | "string";

export type VariableScalar = boolean | number | string;

export type VariableValue = VariableScalar | Array<ThemedValue>;
