//! Build-time derivation of `BUILD_SALT` for the AI Action Surface.
//!
//! Spec `2026-04-24-ai-action-surface.md` §3.1: `shortHash`'s salt
//! must come from a **compile-time constant**, not runtime state, so
//! the `derive_actions(doc, build_salt)` output is bitwise stable
//! within one build and predictably shifts across builds.
//!
//! Source priority:
//!   1. `JIAN_BUILD_SALT` env var — explicit override for CI / reproducible
//!      builds / multi-host shared identity.
//!   2. `git rev-parse --short=16 HEAD` + Cargo semver — default, picks up
//!      every commit so dev rebuilds get distinct salts.
//!   3. Cargo semver alone — fallback when git is unavailable (tarball
//!      builds, vendored sources).
//!
//! The chosen source string is hashed with two FNV-1a rounds (different
//! offset bases) to produce 16 bytes. Same algorithm family as the
//! runtime `short_hash` (`naming.rs`), so we keep dependencies at zero —
//! no `blake3` etc. needed during the build script.

use std::env;
use std::path::PathBuf;
use std::process::Command;

const FNV_OFFSET_A: u64 = 0xcbf2_9ce4_8422_2325;
const FNV_OFFSET_B: u64 = 0x1234_5678_9abc_def0;
const FNV_PRIME: u64 = 0x100_0000_01b3;

fn fnv1a_64(seed: u64, bytes: &[u8]) -> u64 {
    let mut h = seed;
    for b in bytes {
        h ^= *b as u64;
        h = h.wrapping_mul(FNV_PRIME);
    }
    h
}

fn derive_salt(source: &str) -> [u8; 16] {
    let bytes = source.as_bytes();
    let h1 = fnv1a_64(FNV_OFFSET_A, bytes);
    let h2 = fnv1a_64(FNV_OFFSET_B, bytes);
    let mut out = [0u8; 16];
    out[..8].copy_from_slice(&h1.to_le_bytes());
    out[8..].copy_from_slice(&h2.to_le_bytes());
    out
}

fn git_head() -> Option<String> {
    let out = Command::new("git")
        .args(["rev-parse", "--short=16", "HEAD"])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let s = String::from_utf8(out.stdout).ok()?.trim().to_owned();
    if s.is_empty() {
        None
    } else {
        Some(s)
    }
}

fn resolve_source() -> String {
    if let Ok(explicit) = env::var("JIAN_BUILD_SALT") {
        return explicit;
    }
    let ver = env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.0.0".to_owned());
    match git_head() {
        Some(git) => format!("{git}-{ver}"),
        None => ver,
    }
}

fn main() {
    let source = resolve_source();
    let salt = derive_salt(&source);

    let hex_array = salt
        .iter()
        .map(|b| format!("0x{b:02x}"))
        .collect::<Vec<_>>()
        .join(", ");

    let escaped_source = source.replace('\\', "\\\\").replace('"', "\\\"");

    let generated = format!(
        "// @generated by jian-core/build.rs — do not edit.\n\
         //\n\
         // Source string used to derive `BUILD_SALT`. Exposed for audit logs\n\
         // and Codex review; the salt itself is a one-way 16-byte FNV-1a\n\
         // double-hash of this string.\n\
         pub const BUILD_SALT_SOURCE: &str = \"{escaped_source}\";\n\
         \n\
         /// 16-byte salt fed to `short_hash` (`naming.rs`). Compile-time\n\
         /// constant per spec §3.1.\n\
         pub const BUILD_SALT: [u8; 16] = [{hex_array}];\n"
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let dest = out_dir.join("build_salt.rs");
    std::fs::write(&dest, generated).expect("write build_salt.rs");

    // Re-run when the override env var or git HEAD changes. We deliberately
    // do NOT `rerun-if-changed=src/` etc. — the salt only depends on these
    // two inputs, and over-broad rerun directives slow incremental builds.
    println!("cargo:rerun-if-env-changed=JIAN_BUILD_SALT");
    println!("cargo:rerun-if-changed=build.rs");
    emit_git_rerun_directives();
}

/// Emit `cargo:rerun-if-changed` directives so the build script re-runs
/// when the working git state changes.
///
/// Naively watching `.git/HEAD` is wrong: on a branch, HEAD only stores
/// `ref: refs/heads/<name>`, so a new commit on the same branch updates
/// `.git/refs/heads/<name>` but **not** HEAD — `BUILD_SALT` would go
/// stale until something else triggered a rebuild. We watch both:
///
///   1. `.git/HEAD` — covers branch switches, detached-HEAD moves.
///   2. The branch ref file pointed to by HEAD — covers commits on the
///      current branch.
///
/// Edge cases handled:
///   - **Worktrees / submodules:** `.git` is a *file* containing
///     `gitdir: <path>`. We resolve it and watch HEAD inside the
///     resolved gitdir.
///   - **Vendored sources:** no `.git` at all. We silently skip; cargo
///     ignores missing paths in `rerun-if-changed`.
fn emit_git_rerun_directives() {
    let manifest_dir = match env::var_os("CARGO_MANIFEST_DIR") {
        Some(d) => PathBuf::from(d),
        None => return,
    };
    // Workspace layout: `crates/jian-core/Cargo.toml` → repo root is `../../`.
    let repo_root = manifest_dir.join("..").join("..");
    let gitdir = match resolve_gitdir(&repo_root.join(".git")) {
        Some(d) => d,
        None => return,
    };
    let head_path = gitdir.join("HEAD");
    println!("cargo:rerun-if-changed={}", head_path.display());

    // Read HEAD to find the ref file. If HEAD is a detached commit hash,
    // watching HEAD itself is enough — every detached move rewrites it.
    if let Ok(head_contents) = std::fs::read_to_string(&head_path) {
        if let Some(rest) = head_contents.trim().strip_prefix("ref: ") {
            let ref_path = gitdir.join(rest);
            println!("cargo:rerun-if-changed={}", ref_path.display());
        }
    }
}

/// Resolve `.git` into its actual gitdir. For a normal repo `.git` is
/// itself a directory and we return it as-is. For a worktree or
/// submodule `.git` is a file containing `gitdir: <path>`; we follow
/// the indirection. Returns `None` when neither shape is present.
fn resolve_gitdir(dot_git: &std::path::Path) -> Option<PathBuf> {
    let meta = std::fs::metadata(dot_git).ok()?;
    if meta.is_dir() {
        return Some(dot_git.to_path_buf());
    }
    if meta.is_file() {
        let body = std::fs::read_to_string(dot_git).ok()?;
        let raw = body.trim().strip_prefix("gitdir:")?.trim();
        let candidate = PathBuf::from(raw);
        let resolved = if candidate.is_absolute() {
            candidate
        } else {
            // The `gitdir:` path is relative to the file's parent.
            dot_git.parent()?.join(candidate)
        };
        return Some(resolved);
    }
    None
}
