#!/usr/bin/env bash
# Register the `.op` MIME-type on a user's Linux session (Plan 8
# §T7 / C7). The .deb / .rpm / AppImage installers also do this via
# their packaging metadata; this script handles the
# `tar.gz`-from-`get.jian.dev/install.sh` install path where no
# package manager runs the post-install hook.
#
# Codex round 1 MEDIUM: `jian://` URL-scheme handling
# (`x-scheme-handler/jian`) is intentionally NOT registered here.
# The `.desktop` file at `packaging/linux/jian.desktop` mirrors that
# decision — `jian player` rejects bare deep-link URIs because they
# target a *running* peer, not a fresh document load. Re-add the
# `xdg-mime default jian.desktop x-scheme-handler/jian` call once
# single-instance forwarding lands.
#
# Idempotent — re-running updates the cached MIME database without
# duplicating registrations.
#
# Usage:
#   ./packaging/linux/install-mime.sh                    # user-scope
#   sudo ./packaging/linux/install-mime.sh --system      # system-scope

set -euo pipefail

SCOPE="user"
if [[ "${1:-}" == "--system" ]]; then
    SCOPE="system"
fi

ROOT="$(cd "$(dirname "$0")"/../.. && pwd)"

# Pick install prefixes. User-scope writes under `~/.local`; system-
# scope writes under `/usr/local` (or `/usr/share/...` for distro
# packages — but a curl|sh install isn't a distro package, so /usr/local
# is the right default).
if [[ "$SCOPE" == "user" ]]; then
    APP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
    MIME_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/mime/packages"
    ICON_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor/512x512/apps"
else
    APP_DIR="/usr/local/share/applications"
    MIME_DIR="/usr/local/share/mime/packages"
    ICON_DIR="/usr/local/share/icons/hicolor/512x512/apps"
fi

mkdir -p "$APP_DIR" "$MIME_DIR" "$ICON_DIR"

cp "$ROOT/packaging/linux/jian.desktop" "$APP_DIR/jian.desktop"
cp "$ROOT/packaging/linux/jian.mime.xml" "$MIME_DIR/jian.mime.xml"

# Icon: ship the 1024×1024 source PNG; downscale variants are
# generated by `gtk-update-icon-cache` consumers when needed. The
# .desktop file references `Icon=jian` (no extension, no path), which
# the icon-theme stack resolves through the hicolor index.
if [[ -f "$ROOT/packaging/icon/AppIcon-source.png" ]]; then
    cp "$ROOT/packaging/icon/AppIcon-source.png" "$ICON_DIR/jian.png"
fi

# Refresh caches. `update-mime-database` is mandatory; the others
# are best-effort (older distros don't ship them).
update-mime-database "$(dirname "$MIME_DIR")" 2>/dev/null || true
update-desktop-database "$APP_DIR" 2>/dev/null || true
gtk-update-icon-cache --quiet --force \
    "$(dirname "$(dirname "$ICON_DIR")")" 2>/dev/null || true

# Tell xdg-mime that `jian.desktop` claims `.op`. xdg-mime is the
# user-facing interface; under the hood it edits
# `mimeapps.list`. `xdg-mime default` requires both arguments.
if command -v xdg-mime >/dev/null 2>&1; then
    xdg-mime default jian.desktop application/x-jian-op || true
fi

echo "install-mime: registered .op + jian.desktop in $SCOPE scope"
echo "  applications: $APP_DIR"
echo "  mime:         $MIME_DIR"
echo "  icon:         $ICON_DIR"
